### ISSUE TITLE
   motu.datastore.set() throws _iteratorError

### ISSUE THREAD

**Issue by isaacOstler** [delbeke/motujs#1]
`motu.datastore.set('mix/chan/0/matrix/fader', Math.random())`
throws the following error:
```

/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/datastore.js:112
              throw _iteratorError;
              ^

ReferenceError: FormData is not defined
    at exports.default (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/http/patch.js:8:18)
    at Motu._setNewData (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/motu.js:112:27)
    at Motu._onDatastoreChanged (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/motu.js:83:14)
    at Datastore.<anonymous> (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/motu.js:37:13)
    at Datastore.emit (/Users/farpoint/testCode/midiTest/node_modules/eventemitter3/index.js:130:35)
    at Datastore._emitChanges (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/datastore.js:124:14)
    at _loop (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/datastore.js:94:16)
    at Timeout._onTimeout (/Users/farpoint/testCode/midiTest/node_modules/motujs/lib/datastore.js:98:13)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)

```
I'm probably missing something obvious, I was just playing around with the examples.
Thanks

**Comment by alexanderson1993** [comment]
Sorry to be late to the party, but it looks like you were trying to use this module on Node. Browsers have a global `FormData` constructor object; Node does not. I think that means this library is meant to be used on the Browser. 

It might be worthwhile seeing if you can use a FormData implementation (such as this one: https://www.npmjs.com/package/form-data) as a shim on Node.
